update install

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -27,6 +27,89 @@ fail () {
   exit
 }
 
+install_cli_tools() {
+  # There's not need to install XCode tools on Linux
+  if [ `uname` == 'Linux' ]; then
+    return
+  fi
+
+  info "Trying to detect installed Command Line Tools..."
+
+  if ! [ $(xcode-select -p) ]; then
+    echo "You don't have Command Line Tools installed!"
+    read -p "Do you agree to install Command Line Tools? [y/N] " -n 1 answer
+    echo
+    if [ ${answer} != "y" ]; then
+      exit 1
+    fi
+
+    info "Installing Command Line Tools..."
+    echo "Please, wait until Command Line Tools will be installed, before continue."
+
+    xcode-select --install
+  else
+    success "Seems like you have installed Command Line Tools. Skipping..."
+  fi
+
+  finish
+}
+
+install_homebrew() {
+  # There's not need to install Homebrew on Linux
+  if [ `uname` != 'Darwin' ]; then
+    return
+  fi
+
+  info "Trying to detect installed Homebrew..."
+
+  if ! _exists brew; then
+    echo "Seems like you don't have Homebrew installed!"
+    read -p "Do you agree to proceed with Homebrew installation? [y/N] " -n 1 answer
+    echo
+    if [ ${answer} != "y" ]; then
+      exit 1
+    fi
+
+    info "Installing Homebrew..."
+    ruby -e "$(curl -fsSL ${HOMEBREW_INSTALLER_URL})"
+    brew update
+    brew upgrade
+  else
+    success "You already have Homebrew installed. Skipping..."
+  fi
+
+  finish
+}
+
+install_git() {
+  info "Trying to detect installed Git..."
+
+  if ! _exists git; then
+    echo "Seems like you don't have Git installed!"
+    read -p "Do you agree to proceed with Git installation? [y/N] " -n 1 answer
+    echo
+    if [ ${answer} != "y" ]; then
+      exit 1
+    fi
+
+    info "Installing Git..."
+
+    if [ `uname` == 'Darwin' ]; then
+      brew install git
+    elif [ `uname` == 'Linux' ]; then
+      sudo apt-get install git
+    else
+      error "Error: Failed to install Git!"
+      exit 1
+    fi
+  else
+    success "You already have Git installed. Skipping..."
+  fi
+
+  finish
+}
+
+
 setup_gitconfig () {
   if ! [ -f git/gitconfig.local.symlink ]
   then
@@ -49,6 +132,46 @@ setup_gitconfig () {
   fi
 }
 
+install_zsh() {
+  info "Trying to detect installed Zsh..."
+
+  if ! _exists zsh; then
+    echo "Seems like you don't have Zsh installed!"
+    read -p "Do you agree to proceed with Zsh installation? [y/N] " -n 1 answer
+    echo
+    if [ ${answer} != "y" ]; then
+      exit 1
+    fi
+
+    info "Installing ZSH..."
+
+    if [ `uname` == 'Darwin' ]; then
+      brew install zsh zsh-completions
+    elif [ `uname` == 'Linux' ]; then
+      sudo apt-get install zsh
+    else
+      error "Error: Failed to install Zsh!"
+      exit 1
+    fi
+  else
+    success "You already have Zsh installed. Skipping..."
+  fi
+
+  if _exists zsh; then
+    info "Setting up Zsh as default shell..."
+
+    echo "The script will ask you the password for sudo 2 times:"
+    echo
+    echo "1) When adding fish shell into /etc/shells via tee"
+    echo "2) When changing your default shell via chsh -s"
+    echo
+
+    echo "$(command -v zsh)" | sudo tee -a /etc/shells
+    chsh -s "$(command -v zsh)" || error "Error: Cannot set Zsh as default shell!"
+  fi
+
+  finish
+}
 
 link_file () {
   local src=$1 dst=$2
@@ -137,7 +260,11 @@ install_dotfiles () {
   done
 }
 
+install_cli_tools
+install_homebrew
+install_git
 setup_gitconfig
+install_zsh
 install_dotfiles
 
 # If we're on a Mac, let's install and setup homebrew.
